// Generate a safe, human-readable receipt label when a receipt has no real
// invoice/reference number. This is a DISPLAY/storage fallback only — it must
// never be presented to the user as an "OCR-detected invoice number".
//
// The DB currently requires a non-empty invoiceNumber; until that becomes
// optional (Stage B/C: receiptLabel/documentReference), this keeps no-invoice
// receipts (bank/ATM, cash slips) saveable without a cryptic validation error.

function slugifyMerchant(merchant: string): string {
  const slug = merchant
    .normalize("NFKD")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 32);
  return slug || "Receipt";
}

/**
 * Build a label like "McDonalds-2018-01-01" or "Receipt-2024-06-11".
 * - `merchant`: best merchant guess ("" when unknown → "Receipt").
 * - `date`: YYYY-MM-DD if known; otherwise today's date is used.
 */
export function generateReceiptLabel(
  merchant: string | null | undefined,
  date: string | null | undefined,
  today: () => string = () => new Date().toISOString().slice(0, 10),
): string {
  const slug = slugifyMerchant((merchant ?? "").trim());
  const datePart =
    date && /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : today();
  return `${slug}-${datePart}`;
}

/** True when a value generated by generateReceiptLabel-style logic, not OCR. */
export function isGeneratedReceiptLabel(value: string): boolean {
  return /-\d{4}-\d{2}-\d{2}$/.test(value);
}
